# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.event.pusher.email != 'github-action@noreply.com'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
        
      - name: Get Latest FlossWare Scripts
        run: |
          cd ${GITHUB_WORKSPACE}/flossware-scripts
          git checkout .
          cd -
          git submodule foreach git checkout master
          git submodule foreach git pull
          git submodule update --remote --merge

      - name: Setup Git Config
        run: | 
          git config --global user.name "Git Action"
          git config --global user.email github-action@noreply.com
          
      - name: Rev Spec File
        run: ${GITHUB_WORKSPACE}/flossware-scripts/bash/continuous-delivery/prepare-rpm-git-release.sh flossware.spec

      - name: Build RPM
        run: ${GITHUB_WORKSPACE}/buildrpm.sh ${GITHUB_WORKSPACE}/../rpmbuilds

      - name: Push Git Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

              #- name: Commit/Push Git Repo
              #run: ${GITHUB_WORKSPACE}/flossware-scripts/bash/git/push-current-branch-to-gitrepo.sh

        # git push origin `compute-git-current-branch` --tags            
        
      - name: Publish to Bintray
        run: ${GITHUB_WORKSPACE}/flossware-scripts/bash/bintray/rpm-publish.sh --bintrayUser sfloess --bintrayKey ${{ secrets.BINTRAY_API_KEY }} --bintrayAccount flossware --bintrayRepo rpm --bintrayPackage cobbler --bintrayFile ${GITHUB_WORKSPACE}/../rpmbuilds/rpm/RPMS/noarch/`ls -t ${GITHUB_WORKSPACE}/../rpmbuilds/rpm/RPMS/noarch  | head -1` --bintrayContext flossware.spec
          
        
          
        