# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.event.pusher.email != 'github-action@noreply.com'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Git Config
        run: | 
          git config --global user.name "Git Action"
          git config --global user.email github-action@noreply.com
          
      - name: Rev Spec File
        run: ls ${GITHUB_WORKSPACE}/flossware-scripts
          
      - name: Setup JFrog for Bintray
        uses: jfrog/setup-jfrog-cli@v1gvim 
          
        
