# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.event.pusher.email != 'github-action@noreply.com'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup 
        run: |
          #cd ${GITHUB_WORKSPACE}
          #${GITHUB_WORKSPACE}/../FlossWare-scripts/bash/continuous-delivery/prepare-rpm-git-release.sh flossware.spec
          #./buildrpm.sh ${GITHUB_WORKSPACE}/../rpmbuilds
          #${GITHUB_WORKSPACE}/../FlossWare-scripts/bash/git/push-current-branch-to-gitrepo.sh &&
          #${GITHUB_WORKSPACE}/../FlossWare-scripts/bash/bintray/rpm-publish.sh --bintrayUser sfloess --bintrayKey ${{ secrets.BINTRAY_API_KEY }} --bintrayAccount flossware --bintrayRepo rpm --bintrayPackage cobbler --bintrayFile ${GITHUB_WORKSPACE}/../rpmbuilds/rpm/RPMS/noarch/`ls -t ${GITHUB_WORKSPACE}/../rpmbuilds/rpm/RPMS/noarch  | head -1` --bintrayContext flossware.spec
