# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.event.pusher.email != 'github-action@noreply.com'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup 
        run: |
          env
          echo "Here is our workspace: ${GITHUB_WORKSPACE}"
